# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 0.00.01

formats: all

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
    # If your docs or bash scripts need other system dependencies to build, 
    # you can define them here using custom build commands, but usually, this is enough.

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# # We recommend specifying your dependencies to enable reproducible builds
# python:
#   install:
#     - requirements: docs/requirements.txt