"""
Purpose: Generates an AlphaGenome (AG) finetuning .yaml config file. 
        It maps modalities to directories, grabs BigWig files, strips tags,
        and pulls in precomputed non-zero track means to format the head configs.
Input:   --data_dir (Base path to BigWig input directories)
        --config_prefix (Output path/prefix for the YAML file)
        --modality_folders (Space-separated list of subfolders like multiome_ATAC_bigwig multiome_RNA_bigwig)
        --nonzero_means (CSV generated by the bash script)
        --norm_tag (Optional tag to filter BigWig filenames by, tagged ones are kept, tag is removed from name.)
Output:  A formatted .yaml configuration file for AlphaGenome finetuning
"""

import os
import yaml
import argparse
import pandas as pd
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Generate AG finetuning YAML config")
    
    # Core I/O arguments
    parser.add_argument("--data_dir", type=str, required=True, 
                        help="Base path to bigwig input data directories")
    parser.add_argument("--config_prefix", type=str, default="config.yaml", 
                        help="Path and name of the output YAML file")
    
    # Using nargs='+' allows the user to pass multiple folders like: --modality_folders ATAC RNA
    parser.add_argument("--modality_folders", type=str, nargs='+', required=True, 
                        help="List of subfolders in data_dir corresponding to modalities. Must contain ATAC, RNA, or CutnTag in name.")
    parser.add_argument("--nonzero_means", type=str, default="input_data/metadata/bw_nonzero_means.csv",  
                        help="CSV file generated by 00_compute_nonzero_means_per_bw.sh")
    
    # Optional filtering argument
    parser.add_argument("--norm_tag", type=str, default=None, 
                        help="Tag to filter and clean normalized bigwig files (default: None)")
    
    args = parser.parse_args()
    
    DATA_DIR = Path(args.data_dir)
    out_prefix = Path(args.config_prefix)
    nonzero_means_dir = Path(args.nonzero_means)
    modality_folders = args.modality_folders
    
    NONZERO_MEANS = pd.read_csv(nonzero_means_dir)
    
    # Safely create the parent directory for the output file if it doesn't already exist
    out_prefix.parent.mkdir(parents=True, exist_ok=True)

    modality_configs = []
    
    for mod in modality_folders:
        # Infer the correct ID and kind based on standardized naming conventions
        mod_upper = mod.upper()
        if any(tag in mod_upper for tag in ["CUTNTAG", "CUT&TAG", "CNT", "C&T"]):
            id = "CutnTag"
            kind = "atac"
        elif "ATAC" in mod_upper:
            id = "multiome_ATAC"
            kind = "atac"
        elif "RNA" in mod_upper:
            id = "multiome_RNA"
            kind = "rna_seq"
        else:
            raise ValueError(f"'{mod}' does not match any recognized modalities (CutnTag, ATAC, or RNA).")

        target_dir = DATA_DIR / mod
        targets = []
        
        if target_dir.exists():
            # Glob all BigWigs and sort alphabetically to ensure deterministic ordering in the YAML
            for bw_file in sorted(target_dir.glob("*.bw")):
                label = bw_file.name.replace(".bw", "")
                
                if args.norm_tag:
                    # Skip files that don't match our desired normalization tag
                    if args.norm_tag not in label: 
                        continue
                    # Clean the label for the final config by stripping out the tag
                    label = label.replace(args.norm_tag, "")
                
                expected_path = f"{target_dir}/{bw_file.name}"
                
                # Verify that we actually have a precomputed mean for this specific file to prevent silent downstream errors
                match = NONZERO_MEANS.loc[NONZERO_MEANS["full_path"] == expected_path]
                assert not match.empty, f"Input .bw file {expected_path} not found in nonzero track means CSV."
                
                # Extract and round the mean
                nonzero_mean = match["nonzero_mean_canonical"].values[0]
                nonzero_mean = round(float(nonzero_mean), 3)           

                targets.append({
                    "path": str(bw_file.resolve()),
                    "label": label,
                    "nonzero_mean": nonzero_mean
                })
        else:
            print(f"Warning: Could not find directory {target_dir}")
            
        if not targets: 
            print(f"Warning: No valid .bw files found in {target_dir}")

        # Construct the head dictionary expected by AlphaGenome
        head_config = {
            "dir_name": mod,
            "id": id,
            "kind": kind,
            "targets": targets
        }
        modality_configs.append(head_config)

    # Wrap the heads in the top-level configuration key
    final_config = {"heads": modality_configs}

    with open(out_prefix, "w") as f:
        # default_flow_style=False enforces clean, block-style YAML formatting 
        # sort_keys=False preserves the logical order we defined above rather than forcing alphabetical keys
        yaml.dump(final_config, f, default_flow_style=False, sort_keys=False)

if __name__ == "__main__":
    main()